### ISSUE TITLE
Vx, Vy fields

### ISSUE THREAD

**Issue by yujingyan222** [mmolero/SimNDT#14]
Dear @mmolero,
Thanks for your contribution. It is very useful to simulate data. However, I don't know the meaning of Vx, Vy fields while saving them. Could you please help me figure it? Thanks a lot!

**Comment by mmolero** [comment]
The computed velocity components at each grid point, you can find more information about the model in [Optimized OpenCL implementation of the Elastodynamic Finite Integration Technique for viscoelastic media](https://d1wqtxts1xzle7.cloudfront.net/49231214/Optimized_OpenCL_implementation_of_the_E20160930-22295-cg7u12-libre.pdf?1475219898=&response-content-disposition=inline%3B+filename%3DOptimized_OpenCL_implementation_of_the_E.pdf&Expires=1662407157&Signature=fOmw~Cs-sUDD47CmnvxvLRdWX5I8fr~XWy97czLOJdkqnYxIlTAF83cmyiGsDA8FoqmBdiy3doeiP97sghOS22qJG0t3FWAneeM2Its5nPtIS1D3SNc9BXk2VjSn-Cf3ItkssrEG4noFlo4xKAw3hXl69-5bzYVncxOCEuIAhH6SmGKm1V-zPftnMcd-g8cNvvHWwEAsg13n9WszNJhRS6S7eCedqieJ6kwQqGFQ3L7MIyjOx8lQ2wSpsdxPh~ja7eMKVB0Kw2186d-xggiuHK69Rg4JjGbVWXGEjt-7NdNBjdJ9r3elJDkKgPzOdEv2oBQCg1gbhHSwAPMTPdLxVQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)

**Comment by yujingyan222** [comment]
Dear @mmolero ,
Thanks for your reply. I will check the detailed information. In addition, could I use SimNDT to asonic ultrasound wave propogation? In asonic wave equation, the output of it is pressure field. I don't know how to deal with it. Hope to receive your reply. Thank a lot!

> The computed velocity components at each grid point, you can find more information about the model in [Optimized OpenCL implementation of the Elastodynamic Finite Integration Technique for viscoelastic media](https://d1wqtxts1xzle7.cloudfront.net/49231214/Optimized_OpenCL_implementation_of_the_E20160930-22295-cg7u12-libre.pdf?1475219898=&response-content-disposition=inline%3B+filename%3DOptimized_OpenCL_implementation_of_the_E.pdf&Expires=1662407157&Signature=fOmw~Cs-sUDD47CmnvxvLRdWX5I8fr~XWy97czLOJdkqnYxIlTAF83cmyiGsDA8FoqmBdiy3doeiP97sghOS22qJG0t3FWAneeM2Its5nPtIS1D3SNc9BXk2VjSn-Cf3ItkssrEG4noFlo4xKAw3hXl69-5bzYVncxOCEuIAhH6SmGKm1V-zPftnMcd-g8cNvvHWwEAsg13n9WszNJhRS6S7eCedqieJ6kwQqGFQ3L7MIyjOx8lQ2wSpsdxPh~ja7eMKVB0Kw2186d-xggiuHK69Rg4JjGbVWXGEjt-7NdNBjdJ9r3elJDkKgPzOdEv2oBQCg1gbhHSwAPMTPdLxVQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)

**Comment by mmolero** [comment]
I believe you can, with this simulator you can simulate fluid medium as main propagation media.  Perhaps, the transducer simulation is not quiet good but you can try

**Comment by yujingyan222** [comment]
> I believe you can, with this simulator you can simulate fluid medium as main propagation media. Perhaps, the transducer simulation is not quiet good but you can try

Dear @mmolero , 
Very glad to receive your reply. I will try it. Thanks a lot!!!
