### ISSUE TITLE
Stable V0.42 version available?

### ISSUE THREAD

**Issue by mauh2** [mmolero/SimNDT#2]
Hi Miguel,

I just found your amazing ultrasound simulator while searching for a good Wave2000 replacement. Unfortunately the program is telling me "Error in the object generation!!!" when trying to create my first rectangle. Do I have to install a special phyton version?
Your demo in youtube was running with version 0.42 and looks very stable.
Is it possible to get this version?

Kind regards,
Markus

**Comment by mauh2** [comment]
Yes, I installed the 0.5 release exe on a windows10 (64bit) laptop. I will try it tomorrow on other computers...

**Comment by mmolero** [comment]
If you are running from the exe file you don’t need to have installed  any python distribution in your computer.  Could you please enumerate the steps you are following in order to replicate this issue 
Thanks

**Comment by mauh2** [comment]
I tried it on two more computers. Same effect:
- Install setup-SimNDT-v0.5.exe
- Start
- New Simulation
- New Scenario (20, 10, 10, 0)
- Add Rectangle (5, 5, 2, 2, 0, 100) => "Error in the object generation!!!"

But I can create ellipses.
I can add materials.
I can setup boundaries

But in the "Single Launch Setup" there are some things which dont work:
- Transducer Location is grayed out
- The buttons "Preview Transducer setup" and "Signal Parameters" do nothing (no window comes up)

**Comment by mmolero** [comment]
Thanks, this week I’m out
But this weekend will come back so I hope new week I can solve it

**Comment by mmolero** [comment]
I've detected two issues:

- the rectangle generation.
- the actions which show the modals: "Preview Transducer setup" and "Signal Parameters" 

Please keep in mind that is not able to change the Transducer Location, this is a read-only information. Only Top position is permitted.

**Comment by mmolero** [comment]
@mauh2 I've updated the release with the fixed executable. Please download and install again. 

I had to compile using python2.7 in order to solve the issues related to the modal windows.

**Comment by mmolero** [comment]
if you find new issues please open other ones. Thanks!
