### ISSUE TITLE
¿Funciona?

### ISSUE THREAD

**Issue by JuanIgnacioCG** [mmolero/SimNDT#4]
Hola M Molero,
estoy haciendo mi PhD en ultrasonidos por pulso-eco para material compuesto y me encantaría poder utilizar tu SimNDT, ¿Crees que funcionaría?

**Comment by mmolero** [comment]
Hola Juan 
Si te puede servir dependerá del modelo y situación que quieras simular. Que es exactamente lo que quieres hacer ?

**Comment by JuanIgnacioCG** [comment]
> 
> 
> Hola Juan
> Si te puede servir dependerá del modelo y situación que quieras simular. Que es exactamente lo que quieres hacer ?

Me gustaría simular porosidad en pulso eco.

**Comment by mmolero** [comment]
Que frecuencia utilizarás? De que tamaño son los poros? Si usas más de 5 MHz necesitaras una gpu para que la simulación no tarde mucho.

**Comment by JuanIgnacioCG** [comment]
> 
> 
> Que frecuencia utilizarás? De que tamaño son los poros? Si usas más de 5 MHz necesitaras una gpu para que la simulación no tarde mucho.

¿Sería posible ponernos en contacto por un medio más sencillo de intercambiar mensajes? 

Tengo varias posibilidades de frecuencia. Por GPU tampoco hay problema.

**Comment by mmolero** [comment]
miguel.molero at Gmail
